### ISSUE TITLE
留言板

### ISSUE THREAD

**Issue by rbuli** [rbuli/rbuli.github.io#3]
# 欢迎：）
>http://cssmini.com
>p.s：暂时不打算在博客内开启留言的模块

**Comment by far310** [comment]
路过 看看

**Comment by wenhai2000** [comment]
楼主好帅

**Comment by rbuli** [comment]
@far310  欢迎~

**Comment by rbuli** [comment]
@wenhai2000  嘘~小声点

**Comment by mangococo** [comment]
那个，楼主，如下，看来你的博客已被百度收录，请问你后来的域名解析是怎么处理的呢？如何让同一域名海外访问github.io，大陆访问coding.net？请赐教。
![](http://pilek1ll1.bkt.clouddn.com/2018-11-26-15431825561161.jpg)

**Comment by rbuli** [comment]
> 那个，楼主，如下，看来你的博客已被百度收录，请问你后来的域名解析是怎么处理的呢？如何让同一域名海外访问github.io，大陆访问coding.net？请赐教。
> ![](https://camo.githubusercontent.com/653098133789914691d20baf8f8921cb44a23ed7/687474703a2f2f70696c656b316c6c312e626b742e636c6f7564646e2e636f6d2f323031382d31312d32362d31353433313832353536313136312e6a7067)

在域名解析上面配置。
![image](https://user-images.githubusercontent.com/33245169/49053664-028bcf80-f22c-11e8-8987-c09af9f92a94.png)

**Comment by mangococo** [comment]
谢谢您的回复。

rbuli <notifications@github.com> 于 2018年11月27日周二 10:05写道：
